---
title: "David Zhang's CV"
author: David Zhang
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1ufltIQ6ZzLDeDQ6oDjuCuRIZdx95Zn0YNomXwMELG24/edit?usp=sharing",  
  pdf_mode = params$pdf_mode
  
)

CV[["entries_data"]] <- CV[["entries_data"]] %>% 
  dplyr::filter(as.logical(in_cv))

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```

Aside
================================================================================

```{r}
if(params$pdf_mode){
  cat("View this CV online with links at _dzhang32.github.io/cv/_")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/dzhang32/cv/raw/main/dz_cv.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```

Language skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R packages [**datadrivencv**](https://github.com/nstrayer/datadrivencv) and [**pagedown**](https://github.com/rstudio/pagedown). 

The source code is available on [github.com/dzhang32/cv](https://github.com/dzhang32/cv). 

Last updated on `r Sys.Date()`.

Main
================================================================================

David Zhang {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```

Work Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('work_experience')
```

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```

<!-- Research Experience {data-icon=laptop} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r} -->
<!-- CV %<>% print_section('research_positions') -->
<!-- ``` -->

<!-- <br> -->
<!-- <br> -->

Software & programming {data-icon=chart-line}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('software')
```

Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('teaching_positions')
```

Selected Publications {data-icon=book}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('publications_aside')
```
:::

```{r}
CV %<>% print_section('academic_articles')
```

```{r}
CV %<>% print_links()
```

